name: nushell
base: core24
license: MIT
source-code: https://github.com/sed-i/nushell-snap
issues: https://github.com/sed-i/nushell-snap/issues
adopt-info: nushell  # Note: snap version is set from tag

title: Nushell
icon: nushell-original.png
website: https://www.nushell.sh/
summary: A new type of shell
description: |
  Rather than being either a shell, or a programming language, Nushell connects both by
  bringing a rich programming language and a full-featured shell together into one package.

confinement: classic
grade: stable

apps:
  nu:
    command: nu
  nu-plugin-stress-internals:
    command: nu_plugin_stress_internals
  nu-plugin-gstat:
    command: nu_plugin_gstat
  nu-plugin-formats:
    command: nu_plugin_formats
  nu-plugin-polars:
    command: nu_plugin_polars
  nu-plugin-query:
    command: nu_plugin_query
  nu-plugin-inc:
    command: nu_plugin_inc
  nu-plugin-example:
    command: nu_plugin_example
  nu-plugin-custom-values:
    command: nu_plugin_custom_values

parts:
  nushell:
    plugin: rust
    source: https://github.com/nushell/nushell.git
    source-tag: "0.98.0"
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --always)"
    build-packages: [libxcb-composite0-dev, pkg-config, libssl-dev, build-essential, musl-tools]
    build-snaps: [rustup]
    build-attributes:
      - enable-patchelf
    override-build: |
      rustup install stable
      cargo build --release --all --features=static-link-openssl

      # Ref: https://github.com/canonical/snapcraft/blob/8faa6d54eef1f4437c7e10337ed8fdcc8dc51cbc/snapcraft_legacy/plugins/v2/rust.py#L194
      find ./target/release -maxdepth 1 -executable -type f -name "nu*" -exec install -Dvm755 {} "${SNAPCRAFT_PART_INSTALL}" ';'
