name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: snapcore/action-build@v1
      id: build
    - run: |
        sudo snap install --dangerous --classic ${{ steps.build.outputs.snap }}
        nu --version
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
